from __future__ import annotations

from dataclasses import dataclass as _dataclass


WINDOW_BUFFER = 0.35
WINDOW_SILL_MIN = 0.72
WINDOW_SILL_MAX = 0.9
WINDOW_HEIGHT_DEFAULT = 1.45
WINDOW_TOP_MIN = 0.52
DOOR_JAMB_MIN = 0.7
ROOF_EXIT_HEIGHT = 2.5
TARGET_STAIR_ANGLE_DEGREES = 34.0
MIN_TREAD_DEPTH = 0.24
MAX_TREAD_DEPTH = 0.34
MIN_LANDING_DEPTH = 1.02
MAX_LANDING_DEPTH = 1.26
FLIGHT_GAP = 0.24
FLIGHT_SIDE_MARGIN = 0.08
STAIR_SUPPORT_THICKNESS = 0.2
STRINGER_THICKNESS = 0.08
RAIL_HEIGHT = 0.96
RAIL_THICKNESS = 0.05
RAIL_POST_SIZE = 0.05
WINDOW_TRIM_WIDTH = 0.14
WINDOW_TRIM_DEPTH = 0.05
WINDOW_PANEL_THICKNESS = 0.026
WINDOW_FRAME_OVERLAP = 0.024
WINDOW_PANEL_OVERLAP = 0.024
WINDOW_WALL_OVERLAP = 0.018
WINDOW_TRIM_INSET = 0.008
WINDOW_FILL_INSET = 0.012
WINDOW_FRAME_PROUD_OFFSET = 0.018
CLOSED_WINDOW_REVEAL_DEPTH = 0.074
INNER_FRAME_PROUD_OFFSET = 0.012
PARAPET_CAP_PROUD_OFFSET = 0.018
LOWER_FACADE_SIGHT_CLEARANCE = 0.16
BALCONY_SLAB_THICKNESS = 0.14
BALCONY_DEPTH = 1.82
BALCONY_RAIL_HEIGHT = 0.94
BALCONY_RAIL_THICKNESS = 0.14
BALCONY_STRIP_EXTRA_SPAN = 1.55
BALCONY_STRIP_DEPTH = 1.96
FACADE_BAND_HEIGHT = 0.2
FACADE_BAND_DEPTH = 0.08
STOOP_DEPTH = 1.25
STOOP_LANDING_HEIGHT = 0.48
STOOP_STEP_COUNT = 4
PODIUM_HEIGHT = 1.22
PODIUM_MARGIN = 0.18
PODIUM_STEP_COUNT = 6
AC_DEPTH = 0.36
AC_FAN_RADIUS = 0.07
AC_FAN_DEPTH = 0.04
ROOF_PROP_EDGE_MARGIN = 0.9
ROOF_PROP_CLEARANCE = 1.25
WALL_PIPE_WIDTH = 0.34
WALL_PIPE_DEPTH = 0.26
WALL_PIPE_CLAMP_HEIGHT = 0.08
WALL_PIPE_STANDOFF = 0.2
WALL_PIPE_TWIN_OFFSET = 0.48
WALL_PIPE_BEND_LENGTH_MIN = 0.74
WALL_PIPE_BEND_LENGTH_MAX = 1.08
ROOF_PIPE_RUN_MIN = 1.55
ROOF_PIPE_RUN_MAX = 3.1
ROOF_PIPE_STANDOFF = 0.18
ROOF_PIPE_EDGE_INSET = 0.82
ROOF_PIPE_BLOCK_MARGIN = 0.22
ROOF_PIPE_RUN_REQUIRED_LONG_DIM_MIN = 10.2
ROOF_PIPE_RUN_REQUIRED_SHORT_DIM_MIN = 7.2
ROOF_PIPE_RUN_SECONDARY_LONG_DIM_MIN = 12.0
ROOF_PIPE_RUN_STRIP_BOUNDS_TOLERANCE = 0.08
ROOF_PIPE_RUN_STRIP_CENTER_TOLERANCE = 0.56
ROOF_PROP_VENT_LARGE_ROOF_DIM_MIN = 10.5
ENTRY_CANOPY_THICKNESS = 0.12
ENTRY_CANOPY_HEIGHT = 2.45
GROUND_PLINTH_HEIGHT = 0.86
GROUND_PLINTH_DEPTH = 0.18
TOP_SETBACK_HEIGHT = 1.2
TOP_SETBACK_SHELF_THICKNESS = 0.14
ENTRY_DETAIL_PROUD_OFFSET = 0.02
PARAPET_CAP_HEIGHT = 0.08
PARAPET_CAP_DEPTH = 0.06
PARAPET_THICKNESS_SCALE = 1.35
PARAPET_THICKNESS_MIN = 0.22
DOOR_PANEL_DEPTH = 0.02
DOOR_HANDLE_PLATE_DEPTH = 0.03
DOOR_HANDLE_GRIP_DEPTH = 0.04
RUNTIME_MARKER_THICKNESS = 0.12
ROOM_LIGHT_HEIGHT_OFFSET = 0.4
ENTRY_LIGHT_HEIGHT_OFFSET = 2.18
STAIR_LIGHT_HEIGHT_FACTOR = 0.62
LADDER_RAIL_SIZE = 0.08
LADDER_RUNG_SIZE = 0.05
LADDER_CLEAR_WIDTH = 0.48
LADDER_STANDOFF = 0.12
ENTRY_CLEARANCE_MARGIN = 0.22
ROOF_SERVICE_PARAPET_KEEPOUT_MIN = 0.58
ROOF_SERVICE_PARAPET_KEEPOUT_EXTRA = 0.24
ROOF_SERVICE_MARGIN_MIN = 0.45
ROOF_SERVICE_MARGIN_X_RATIO = 0.1
ROOF_SERVICE_MARGIN_Y_RATIO = 0.11
ROOF_EXIT_SERVICE_CLEARANCE = 0.72
ROOF_EXIT_SHELL_MIN_MARKER_COUNT = 7
WIDE_PARTITION_MIN_ROOM_WIDTH = 3.2
WIDE_PARTITION_MIN_WIDTH = 11.8
WIDE_PARTITION_DEPTH_MIN = 5.8
WIDE_PARTITION_OPENING_WIDTH = 1.8
WIDE_PARTITION_OPENING_HEIGHT = 2.35
WIDE_PARTITION_FRAME_DEPTH = 0.12
WIDE_PARTITION_TOP_GAP = 0.08
WIDE_PARTITION_FRAME_PROUD = 0.08
WIDE_PARTITION_FRAME_REVEAL = 0.06

WINDOW_STATE_MASK = "MASK"
WINDOW_STATE_CLOSED = "WINDOW_CLOSED"
WINDOW_STATE_OPEN = "WINDOW_OPEN"
WINDOW_STATE_BALCONY = "BALCONY"
WINDOW_STATE_STAIR = "STAIR_WINDOW"

WINDOW_PROFILE_RESIDENTIAL = "RESIDENTIAL"
WINDOW_PROFILE_RESIDENTIAL_WIDE = "RESIDENTIAL_WIDE"
WINDOW_PROFILE_OFFICE = "OFFICE"
WINDOW_PROFILE_OFFICE_BAND = "OFFICE_BAND"
WINDOW_PROFILE_SMALL_SQUARE = "SMALL_SQUARE"
WINDOW_PROFILE_PANORAMIC = "PANORAMIC"
WINDOW_PROFILE_TALL_NARROW = "TALL_NARROW"
WINDOW_PROFILE_MULTI_PANE = "MULTI_PANE"

ENTRANCE_FLUSH = "FLUSH"
ENTRANCE_STOOP = "STOOP"
ENTRANCE_PODIUM = "PODIUM"
ENTRANCE_STOOP_LOW = "STOOP_LOW"
ENTRANCE_PODIUM_HIGH = "PODIUM_HIGH"

BALCONY_MODE_NONE = "NONE"
BALCONY_MODE_SPARSE = "SPARSE"
BALCONY_MODE_STACKED = "STACKED"
BALCONY_MODE_SHORT = "SHORT"
BALCONY_MODE_STRIP = "STRIP"

MASSING_PROFILE_BOX = "BOX"
MASSING_PROFILE_TOP_SETBACK = "TOP_SETBACK"
MASSING_PROFILE_BASE_HEAVY = "BASE_HEAVY"
MASSING_PROFILE_BALCONY_FACE = "BALCONY_FACE"
MASSING_PROFILE_PILOTIS = "PILOTIS"

GROUND_FLOOR_OPEN_ENTRY = "OPEN_ENTRY"
GROUND_FLOOR_DEFENSIVE_BASE = "DEFENSIVE_BASE"
GROUND_FLOOR_MIXED_WINDOWS = "MIXED_WINDOWS"
GROUND_FLOOR_STOREFRONT = "STOREFRONT"

FRONTAGE_TYPE_GENERIC = "GENERIC"
FRONTAGE_TYPE_HANGAR = "HANGAR"
FRONTAGE_TYPE_STOREFRONT_GENERIC = "STOREFRONT_GENERIC"
FRONTAGE_TYPE_STOREFRONT_SHOP = "STOREFRONT_SHOP"
FRONTAGE_TYPE_STOREFRONT_PHARMACY = "STOREFRONT_PHARMACY"
FRONTAGE_TYPE_STOREFRONT_CLINIC = "STOREFRONT_CLINIC"
FRONTAGE_TYPE_TIMBER_GENERIC = "TIMBER_GENERIC"
FRONTAGE_TYPE_TIMBER_HOUSE = "TIMBER_HOUSE"
FRONTAGE_TYPE_TIMBER_ROWHOUSE = "TIMBER_ROWHOUSE"
FRONTAGE_TYPE_INDUSTRIAL_UTILITY = "INDUSTRIAL_UTILITY"
FRONTAGE_TYPE_INDUSTRIAL_DEPOT = "INDUSTRIAL_DEPOT"
FRONTAGE_TYPE_INDUSTRIAL_WAREHOUSE = "INDUSTRIAL_WAREHOUSE"
FRONTAGE_TYPE_MARKET_HALL = "MARKET_HALL"

_STAGE1_IDENTITY_RESET_PRESETS = {
    "shop_unit",
    "pharmacy",
    "clinic",
    "utility_block",
    "depot",
    "warehouse",
    "hangar",
    "motel",
    "market_hall",
    "under_construction",
}


@_dataclass(frozen=True)
class BalconyPlan:
    leader_idx: int
    member_indices: tuple[int, ...]
    style: str


@_dataclass(frozen=True)
class DoglegMetrics:
    x0: float
    x1: float
    y0: float
    y1: float
    cx: float
    cy: float
    clear_x0: float
    clear_x1: float
    clear_y0: float
    clear_y1: float
    core_width: float
    core_depth: float
    clear_width: float
    flight_width: float
    landing_depth: float
    lower_steps: int
    upper_steps: int
    step_rise: float
    lower_tread: float
    upper_tread: float
    lower_x: float
    upper_x: float
    arrival_side: str
    opposite_side: str
    arrival_wall_y: float
    opposite_wall_y: float
    arrival_landing_y: float
    mid_landing_y: float
    lower_start_y: float
    upper_start_y: float
    lower_direction: float
    upper_direction: float


@_dataclass(frozen=True)
class FrontEntryEnvelope:
    door_width: float
    door_offset_x: float
    door_left: float
    door_right: float
    threshold_z: float
    landing_width: float
    landing_depth: float
    landing_height: float
    landing_front_y: float
    landing_center_y: float
    stair_run: float
    step_count: int
    plinth_exclusion_left: float
    plinth_exclusion_right: float
    front_cut_depth: float
    front_footprint_extent: float
    frontage_variant: str
    frontage_width: float
    recess_depth: float
    cover_depth: float
    canopy_brace_half_span: float
    footprint_left_extent: float
    footprint_right_extent: float
    canopy_width: float
    entry_exclusion_left: float
    entry_exclusion_right: float


@_dataclass(frozen=True)
class ServiceAnchor:
    anchor_id: str
    kind: str
    wall_side: str
    roof_origin_x: float
    roof_origin_y: float
    source_rect: tuple[float, float, float, float] | None
